name: ride_share_app
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Or use the suggested '^3.7.0' if you prefer caret syntax and know your min version

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  geolocator: ^11.0.0 
  google_fonts: ^6.1.0 
  # ... other dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
   # --- Add assets section ---
  assets:
    - assets/images/ # This includes all files in the images folder
  # --- End assets section ---